
library(matlib) # to multiply matrices
library(tidyverse)
library(nleqslv) # to solve non-linear equations
library(zipfR) # beta incomplete function to estimate the area of d-dimensional spherical caps 
library(pracma) # to solve n-dimensional cross products
library(MultitrophicFun)
library(parallel)
library(foreach)
library(doParallel)
library(boot)
library(anisoFun)

# Functions to run calculations about the isotropic area
source("R/matrix_year_i.R")
source("R/isotropy_index.R")


#####################################################################
# ESTIMATION OF THE INPUT PARAMETERS FOR SAAVEDRA ET AL (2017) METRIC
# Metric: variance of the variance of all the values of capital omega 
# generated by removing each of the n-species in the community
# independently
#####################################################################


# We create the metaweb for each year

matrix_entries_raw <- read_csv2("Data/caracoles_raw_data/alpha_heterogeneous_time.csv") %>%
  group_by(year,focal,neighbour) %>% summarise(magnitude = mean(magnitude, na.rm =T))


number_Omega_replicates <- 10000

years_included <- matrix_entries_raw$year %>% unique()

data_saavedra <- NULL

numCores <- detectCores()

registerDoParallel(numCores-4)

set.seed(123)

for(year_i in years_included){
    
    cat(year_i, "\n")
    
    A_int <- matrix_year_i(matrix_entries_raw, year_i)
    
    species <- colnames(A_int)
    cat(species, "\n")
    
    for (species.i in 1:ncol(A_int)) {
      cat(species[species.i], "\n")
      
      A_int_aux_i <- A_int[-species.i,-species.i] 
      omega_sampled <- anisoFun::Omega_bootstrap(A_int_aux_i, number_Omega_replicates)
      
      species_year_i <- tibble(species = species[species.i],
                               Year = year_i,
                               number_species = ncol(A_int),
                               mean_capital_omega= mean(omega_sampled))
      
      
      data_saavedra <- bind_rows(data_saavedra,species_year_i)
      
      write_csv(data_saavedra,
                paste0("Data/caracoles_processed_data/saavedra_asymmetry_data_rep_",
                       number_Omega_replicates,".csv"))
      
    }

  
}


#######################################
#######################################

data_prob_exclusion_caracoles <- read_csv("Data/caracoles_processed_data/caracoles_prob_exclusion_plants_year.csv")
data_saavedra_caracoles  <- read_csv("Data/caracoles_processed_data/saavedra_asymmetry_data_rep_10000.csv")


years_included <- matrix_entries_raw$year %>% unique()

data_comparisson <- NULL

for(year_i in years_included){
  
  prob_exclusion_year_i <- data_prob_exclusion_caracoles %>% filter(year==year_i) 
  saavedra_caracoles_year_i <- data_saavedra_caracoles %>% filter(Year==year_i) %>%
    mutate(small_omega = mean_capital_omega^(1/nrow(prob_exclusion_year_i)))
  asymmetry_index_Allen <- isotropy_index(prob_exclusion_year_i$prob_exclusion)
  correcction_factor_omega <- 2^(nrow(prob_exclusion_year_i)-1) # We add a minus one because omega projections contain n-1 species
  asymmetry_index_saavedra <- var(correcction_factor_omega*saavedra_caracoles_year_i$mean_capital_omega)
  #asymmetry_index_saavedra <- var(saavedra_caracoles_year_i$mean_capital_omega)
  # asymmetry_index_saavedra <- var(saavedra_caracoles_year_i$small_omega)
  
  data_aux <- tibble(year = year_i,
                     asymmetry_index_Allen = asymmetry_index_Allen,
                     asymmetry_index_saavedra = asymmetry_index_saavedra)
  
  data_comparisson <- bind_rows(data_comparisson, data_aux)
  
}

cor.test(data_comparisson$asymmetry_index_saavedra,data_comparisson$asymmetry_index_Allen, method="spearman")
cor.test(data_comparisson$asymmetry_index_saavedra,data_comparisson$asymmetry_index_Allen)

library(scales)
ggplot(data_comparisson, aes(x=asymmetry_index_saavedra,y=asymmetry_index_Allen))+
  geom_point(size=2)+
  labs(x="Asymmetry index proposed in Saavedra et al. (2017)",
       y="Asymmetry index, J'(A)")+
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  theme_bw()+
  theme(
    axis.text.x= element_text(color="black",size=10, vjust=0.5),
    axis.text.y= element_text(color="black", size=12, vjust=0.5),
    axis.title.y = element_text(color="black",size=12, vjust=0.5),
    plot.title = element_text(color="black",face="bold",size=14, hjust=0.5,vjust=1),
    panel.background = element_blank(),
    panel.border = element_rect(linetype = "solid", colour = "black"),
    legend.position="bottom",
    legend.title = element_blank(),
    legend.key = element_rect(fill="white")
  )


